name: main

on: 
  push:
    branches: [ main ]
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: update the code && restart the bot

        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            netstat -tunlp|grep 8080 |awk '{print $7}'|awk -F '/' '{print $1}' | xargs kill -9
            netstat -tunlp|grep 5700 |awk '{print $7}'|awk -F '/' '{print $1}' | xargs kill -9
            cd /home/mostima
            nohup ./go-cqhttp &
            cd Mostima-koishi
            git pull
            npm i
            cd data_handles
            ts-node update.ts
            cd ..
            nohup ts-node app.ts &
